# .readthedocs.yaml

version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"

sphinx:
  configuration: docs/source/conf.py  # Point to the correct conf.py path
  source: docs/source                 # Set the source directory to where your .rst files are
